[build]
  command = "npm install && npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
